vich_uploader:
    db_driver: orm

    mappings:
        recettes_photos:
            uri_prefix: /uploads/photos/recettes
            upload_destination: '%kernel.project_dir%/public/uploads/photos/recettes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        documents:
            uri_prefix: /uploads/documents
            upload_destination: '%kernel.project_dir%/public/uploads/documents'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


        sports_photos:
            uri_prefix: /uploads/photos/sports
            upload_destination: '%kernel.project_dir%/public/uploads/photos/sports'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
